In [26]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  63  43  72  50  87
7   謝欣蓉  女  90  91  90  50  94
8   羅淑芬  女  74  48  50  53  59
9   許美慧  女  42  77  75  62  98
10  廖志豪  男  54  49  46  71  98

In [33]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
9   許美慧  女  42  77  75  62  98
30  楊靜宜  女  45  95  84  47  46
32  蕭怡伶  女  55  41  64  47  69
39  彭美慧  女  57  63  95  57  41
41  許淑芬  女  44  79  84  45  60
43  吳雅萍  女  50  75  84  86  78
47  周美玲  女  54  46  80  63  94