In [ ]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(30, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

           國文         英文         數學         地理         歷史
性別
女   76.952381  66.952381  66.904762  66.714286  70.714286
男   67.724138  70.310345  69.689655  70.310345  71.862069

In [2]:
scores_df

     國文  英文  數學   地理  歷史   姓名 性別
1    49  64  86   53  70  劉彥宏  男
2    42  80  89   92  59  曾彥廷  男
3   100  96  79   97  55  吳子睿  男
4    99  44  50   94  59  蕭志明  男
5    89  86  72   66  66  王文傑  男
6    45  94  51   73  90  朱冠霖  男
7    77  57  57   59  67  謝欣蓉  女
8    99  65  42   72  61  羅淑芬  女
9    51  97  99   57  77  許美慧  女
10   48  56  97   90  53  廖志豪  男
11   44  46  58   48  79  葉柏翰  男
12   93  54  77   56  95  呂承恩  男
13   87  78  50   69  89  蘇雅婷  女
14   83  77  83   67  93  高浩宇  男
15   99  74  78   62  95  王婉茹  女
16   96  71  48   75  87  莊承翰  男
17   70  81  85   75  63  黃裕傑  男
18   52  48  41   78  85  王冠廷  男
19   93  83  93   54  72  呂婉慧  女
20   72  99  56   41  72  莊子謙  男
21   97  73  49   68  74  蘇彥宏  男
22   91  43  54   86  73  李柏融  男
23   57  42  96   57  80  曾明軒  男
24   46  58  96   73  84  呂佳瑩  女
25   97  71  40   77  42  洪怡君  女
26   51  87  86   95  83  洪柏宏  男
27   88  64  55   63  65  江雅琪  女
28   66  70  92   96  54  郭怡萱  女
29   91  60  43   48  92  簡婉慧  女
30   79  96  40   85  88  楊靜宜  女
31   62  54  69   77  84  曾靜儀  女
32   58  71  82   44  80  蕭怡伶  女
33   45  83  83   88  52  洪裕豪  男
34   96  85  44   59  52  簡建宏  男
35   68  41  45   80  76  劉浩然  男
36   42  85  63   41  77  蕭浩宇  男
37   85  53  41   45  71  呂怡靜  女
38   90  92  77   77  80  邱宗翰  男
39   70  49  59   59  40  彭美慧  女
40   45  40  75   48  53  劉靜芬  女
41   98  87  98   57  51  許淑芬  女
42   41  53  84   50  42  邱裕豪  男
43   91  58  52   72  98  吳雅萍  女
44   51  44  82   50  88  施子軒  男
45   58  88  91   42  86  莊柏融  男
46   46  79  56  100  47  鍾浩銘  男
47   65  68  97   90  63  周美玲  女
48   69  53  47   94  59  劉婉婷  女
49   78  57  66  100  61  曾明哲  男
50   71  91  73   41  87  詹柏翰  男

In [4]:
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)

scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0, 250, 350, 500],
    labels=['低分區', '一般區', '高分區']
)

scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count        mean  min  max
性別 總分階級
女  一般區      10  315.200000  287  348
   高分區      11  373.272727  358  402
男  一般區      17  324.235294  279  348
   高分區      12  377.583333  351  414