In [5]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(30, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

           國文         英文         數學         地理         歷史
性別
女   68.571429  54.904762  68.047619  66.857143  55.857143
男   70.068966  61.310345  66.586207  63.896552  66.758621

In [6]:
scores_df

     國文   英文  數學  地理  歷史   姓名 性別
1    61   41  71  63  61  劉彥宏  男
2    84  100  86  94  54  曾彥廷  男
3    51   44  53  72  35  吳子睿  男
4    75   81  59  75  69  蕭志明  男
5    35   57  43  43  95  王文傑  男
6    96   79  74  61  96  朱冠霖  男
7    66   42  79  49  35  謝欣蓉  女
8    96   32  69  63  87  羅淑芬  女
9   100   44  99  65  37  許美慧  女
10   81   80  80  76  66  廖志豪  男
11   58   43  60  40  54  葉柏翰  男
12   66   61  81  39  40  呂承恩  男
13   95   53  67  75  97  蘇雅婷  女
14   99   69  88  84  96  高浩宇  男
15   43   77  52  82  51  王婉茹  女
16   76   44  81  52  65  莊承翰  男
17   60   67  80  31  41  黃裕傑  男
18   88   30  54  33  88  王冠廷  男
19   32   40  80  32  37  呂婉慧  女
20   66   44  83  75  88  莊子謙  男
21   63   65  53  43  58  蘇彥宏  男
22   74   81  88  42  45  李柏融  男
23   31   61  44  54  99  曾明軒  男
24   62   68  45  77  39  呂佳瑩  女
25   93   95  42  63  33  洪怡君  女
26   77   31  67  48  96  洪柏宏  男
27   93   47  58  79  59  江雅琪  女
28   57   65  64  44  83  郭怡萱  女
29   45   82  46  78  46  簡婉慧  女
30   79   65  70  69  61  楊靜宜  女
31   30   37  73  96  95  曾靜儀  女
32   39   64  56  58  97  蕭怡伶  女
33   44   37  36  75  88  洪裕豪  男
34   95   37  61  52  33  簡建宏  男
35   82   85  94  83  43  劉浩然  男
36   70  100  78  98  90  蕭浩宇  男
37   95   42  42  32  34  呂怡靜  女
38   95   30  43  73  61  邱宗翰  男
39   70   33  76  94  35  彭美慧  女
40   31   46  93  52  52  劉靜芬  女
41   80   85  97  85  35  許淑芬  女
42   33   93  79  65  47  邱裕豪  男
43   61   43  91  67  42  吳雅萍  女
44   64   52  40  84  96  施子軒  男
45   99   72  49  91  72  莊柏融  男
46   60   89  97  44  51  鍾浩銘  男
47   93   50  46  83  42  周美玲  女
48   80   43  84  61  76  劉婉婷  女
49   98   36  44  98  65  曾明哲  男
50   51   69  65  65  44  詹柏翰  男

In [9]:
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)

scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0, 250, 350, 500],
    labels=['低分區', '一般區', '高分區']
)
scores_df
scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count        mean  min  max
性別 總分階級
女  低分區       2  233.000000  221  245
   一般區      17  315.529412  271  347
   高分區       2  384.500000  382  387
男  一般區      20  298.300000  255  341
   高分區       9  396.000000  356  436